### ISSUE TITLE
Started seeing 'who to follow'/'topics to follow' again

### ISSUE THREAD

**Issue by deusexcalamus** [insin/tweak-new-twitter#100]
As the subject says.
![image](https://user-images.githubusercontent.com/8674645/155895036-ace25d62-5dff-42f7-9589-4b53812a567b.png)

**Comment by GreenDotBlue99** [comment]
Refresh the page 1

Check extension settings to be sure 2

Go back and refresh again 3

Disable extension and turn it on again then refresh 4

Use ublock origin? Use the zapper tool to make it go away :)

My suggestion as a feature: completely turn of topics, who to follow, etc but keep them in the left menu

**Comment by insin** [comment]
The problem with these is you can't make them show up to test that they're being hidden properly, I haven't seen one in months so closing for now
