### ISSUE TITLE
New algorithmic tweet type: Trending

### ISSUE THREAD

**Issue by southrop** [insin/tweak-new-twitter#102]
Hi,

I've started encountering a new type of algorithmic tweet type called "Trending".

![chrome_2022-03-14_12-17-54](https://user-images.githubusercontent.com/2568167/158099124-36d93002-a5bf-453e-bcf6-f635b0a7ef15.png)

So far I've seen two tweets get inserted into my Home timeline like this. Both of them show up on the Trending explore page too.

![image](https://user-images.githubusercontent.com/2568167/158099258-8899f94f-8db7-45e9-ae9d-8a9f84239b42.png)

SVG path is here:
```
<path d="M8.98 22.698c-.103 0-.205-.02-.302-.063-.31-.135-.49-.46-.44-.794l1.228-8.527H6.542c-.22 0-.43-.098-.573-.266-.144-.17-.204-.393-.167-.61L7.49 2.5c.062-.36.373-.625.74-.625h6.81c.23 0 .447.105.59.285.142.18.194.415.14.64l-1.446 6.075H19c.29 0 .553.166.678.428.124.262.087.57-.096.796L9.562 22.42c-.146.18-.362.276-.583.276z"></path>
```

Full source of the tweet here:
https://gist.github.com/southrop/d64d6b0928e098ff06474f37b30da2f3

**Comment by southrop** [comment]
Just a small update. I didn't have debug mode turned on when I previously saw one of these tweets, but I enabled it now, and it seems like they're currently detected as Retweets

![image](https://user-images.githubusercontent.com/2568167/158312950-ae02f2b6-ff29-4254-b520-70d715fc3d2d.png)

**Comment by GreenDotBlue99** [comment]
If there should be "trending" timeline or extra column for "trending" it should be based on accounts one follows.

At least on user profile pages one can have what's "trending" with that specific user, see this extension called Twemex. Also ThreadHelper has interesting sidebar search functionality.

**Comment by insin** [comment]
I never got this to add it - I don't recommend using the algorithmic timeline options anyway as they cause performance issues due to hiding lots of tweets - these are being moved into the Experiments section next release
