### ISSUE TITLE
Request: Two-column layout for Latest and Shared

### ISSUE THREAD

**Issue by hangedmandesign** [insin/tweak-new-twitter#109]
I don't know how feasible this is, but a feature I'd appreciate would be to have the Latest and Shared Tweets as two side-by-side columns, in a similar vein to Tweetdeck. It would help use up the dead space created by removing all the right-side junk content (I had intended to enable full-width tweets to fill that gap, but doing so on PC it makes some media gigantic.)

Would likely require the left nav to be even more collapsed, so I made a mockup.
![202irefox](https://user-images.githubusercontent.com/15364939/166085079-226da191-653d-416f-a911-dceae0a27fcc.png)

**Comment by GreenDotBlue99** [comment]
Latest: mentions, retweets?

Shared: new original tweets?

**Comment by insin** [comment]
We can't create new functionality like this, as tweets become functionally dead if you try to clone them or move them elsewhere, as all tweet functionality (even setting hover background colours) is driven by React
