### ISSUE TITLE
Request: Twitter lists shortcuts in profiles UI

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/tweak-new-twitter#110]
Add users to Twitter lists as simple click in UI - so that adding a user to a list only needs one click! :)

This worked with the old interface:
https://greasyfork.org/en/scripts/39220-twitter-lists-sidebar
I think in CWS it was called Twitter Lists Redux

**Comment by GreenDotBlue99** [comment]
![c88215d2-bc83-48e3-90b8-6a5146601164.png](https://user-images.githubusercontent.com/82726385/167015469-5dc57d46-7b6e-4c79-82be-115c081d6f79.png)
![7fea3955-a653-44fc-a949-ecada94ee467.png](https://user-images.githubusercontent.com/82726385/167015512-55d268eb-906f-4f63-9960-f99aa0ff48b9.png)
![e702b9bd-407f-492b-9365-c7c452dcd981(2).png](https://user-images.githubusercontent.com/82726385/167015528-2fde1f74-9f54-42d9-a84d-b8a8280db124.png)

**Comment by GreenDotBlue99** [comment]
https://github.com/tomitm/lists

@tomitm

**Comment by insin** [comment]
I don't want to add and maintain any more completely new functionality to Twitter in this extension when it could be done as a separate extension
