### ISSUE TITLE
Request: Redirect link from profile's front page to twitter.com/username/media

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/tweak-new-twitter#111]
Instead of twitter.com/username/

If one opens many profiles to see /media/ and all load to profile front page it's much of extra clicking, loading and waiting ----- instead all opened links could be directly at twitter.com/username/media view 🙂

![137911103-337c2a54-4d00-4af8-a8e3-a2eae5801746.png](https://user-images.githubusercontent.com/82726385/167021259-089139dc-e10e-4ece-bf23-584e27f31f41.png)
![137911343-d4ecafec-ce48-4a8b-b0a2-fdb0db6c4615.png](https://user-images.githubusercontent.com/82726385/167021267-280c1c38-b0fd-4634-be38-0eccff51bea2.png)

**Comment by GreenDotBlue99** [comment]
Some old extension had this feature, but I cannot recall was it some bigger extension for Twitter or small one purpose extension - I think it was in an extension with some other features.

**Comment by insin** [comment]
This is a very... specific feature - other extensions which do generic pattern-based redirection could be used for this
