### ISSUE TITLE
Twitter Media Thumbnails - more than 6 in profile intro?

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/tweak-new-twitter#112]
Show media thumbnails column/gallery on right side of page. More media thumbs than the default 6?

This is an old extension that worked in old Twitter
https://www.crx4chrome.com/extensions/pojmegjgdchmaklfgmcgkhgdgjchidac/#description
![pojmegjgdchmaklfgmcgkhgdgjchidac-screenshot(1).jpg](https://user-images.githubusercontent.com/82726385/167023335-2a667388-37e1-47ab-9256-ad8ef3f17514.jpg)

_(Or such as Twemex adds a sidebar with showing most popular content, similar to that? Worth to look at ThreadHelper too)
_

**Comment by GreenDotBlue99** [comment]
Show more media Thumbnails in user profile pages. displays media thumbnails in the side column on your Twitter web pages.

https://www.crx4chrome.com/extensions/pojmegjgdchmaklfgmcgkhgdgjchidac/#description

![pojmegjgdchmaklfgmcgkhgdgjchidac-screenshot](https://user-images.githubusercontent.com/82726385/179142264-3c7b0139-56da-4354-85ef-256a7e825e79.jpg)

**Comment by insin** [comment]
I think this would require using the Twitter API to add new functionality, which isn't something I want to do this extension
