### ISSUE TITLE
Request: Hide "Discover new Lists" algorithmic section on the "Lists" page.

### ISSUE THREAD

**Issue by nmpsyntax** [insin/tweak-new-twitter#117]
There is a section at the top of the "Lists" page that recommends lists to follow. Considering the nature of this extension, this seems a good place to request an option to hide this. Here is a reference [image](https://i.imgur.com/yguWuIL.png).

**Comment by insin** [comment]
This doesn't seem to be there any more, since Lists was moved to the More menu
