### ISSUE TITLE
When opening a Twitter link from within Tweetdeck, "More Tweets" are still shown

### ISSUE THREAD

**Issue by dfkt** [insin/tweak-new-twitter#119]
When opening any Twitter link from within Tweetdeck (https://tweetdeck.twitter.com), the annoying "More Tweets" are still shown. Is there a way to remove those "More Tweets"? (When copy/pasting the same link into a new tab, "More Tweets" are not shown - refreshing the same tab doesn't help)

--

Vivaldi | 5.2.2623.46 (Stable channel) (64-bit)
Revision | d8227df91188ac735c715e39434d3020e4e44354
OS | Windows 10 Version 21H2 (Build 19044.1706)
JavaScript | V8 10.0.139.17
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.162 Safari/537.36

**Comment by dfkt** [comment]
I managed to bypass this issue by installing the Chrome extension "Referer Control" and blocking referrers to/from https://tweetdeck.twitter.com.

Would be great if removing those referrers could be included in Tweak New Twitter, so I don't have to run yet another extension.

**Comment by ahmetb** [comment]
It appears that this trick is no longer working. https://sourcegraph.com/github.com/insin/tweak-new-twitter@b94c3ab53837fb2c07b8d6b30124724e59958b3a/-/blob/tweak-new-twitter.user.js?L2690-2691

**Comment by henriquemelissopoulos** [comment]
The "More Tweets" section is also showing for me, even without Tweetdeck.

**Comment by insin** [comment]
I'm only seeing "More tweets" if logged out, which Tweak New Twitter doesn't currently support. We had "Discover more" for a while, which I added an option for, then that went away too. Closing for now until this misfeature comes back and stays
