### ISSUE TITLE
Option: user userprofile landing page /media/ etc

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/tweak-new-twitter#124]
Some of the old extension(s) for old interface had this feature as an option, but since removed from Chrome Extension web store.

Redirect/land user profile url clicks such as
https://.twitter.com/username/ to
https://.twitter.com/username/media

username meaning any twitter username url

But when clicked from https://*.twitter.com/username/media to such as /username/with_replies or /username/likes etc. then don't redirect.

Also not to redirect from general twitter menu links such /settings/, /explore/, /bookmarks/ //lists/ etc adding /media to them.

If wanted to, landing page could be either /with_replies/, /media/, /likes/ or if that new /about/ page-timeline is coming. :)

**Comment by GreenDotBlue99** [comment]
It's for people who wants to see that the user has posted, media, not the main "tweets" landing page where there is retweets, mentions, likes, comments etc from content that a user hasn't posted.

When people browse Twitter and open many userprofiles in a new tab, it's frustrating to click the media-link when the page could already be there redirected.

It's a good option. The main landing page is much of distraction and time consuming with all it's extra content.

Reddit Enhancement Suite (RES) has similar option, one can choose from its settings what userprofile/subpage to land.

Chrome Web Store had an extension for old Twitter interface it had a small bunch of features, one was option to redirect to /media/.

**Comment by insin** [comment]
This is a bit too specific of a feature for Tweak New Twitter, it would be better implemented in an extension related to media functionality in Twitter
