### ISSUE TITLE
Individual Topics to follow are back to showing in the timeline

### ISSUE THREAD

**Issue by GitExploraa** [insin/tweak-new-twitter#128]
as the title says, noting that i enabled all the necessary settings to hide them, but they still show, the image below shows an example of what im talking about 
![Screenshot 2022-08-02 223045](https://user-images.githubusercontent.com/44654056/182586942-f417ad74-3cab-4be2-bab6-3df31da4d954.png)

**Comment by insin** [comment]
I'm not seeing these anywhere

**Comment by GitExploraa** [comment]
> I'm not seeing these anywhere

noting that i posted this in June of last year, not surprising that thing changed since then
