### ISSUE TITLE
Tweet and Retweet timeline buttons gone

### ISSUE THREAD

**Issue by Gazzoo-byte** [insin/tweak-new-twitter#133]
Twitter seems to have updated somehow and the Tweet and Retweet timeline buttons have disappeared for me and are no longer clickable.

Using script v57 via ViolentMonkey on Firefox v103.0.2
![image](https://user-images.githubusercontent.com/73721238/184177345-9d0a4657-c745-46ae-8f76-f2873297118b.png)

**Comment by insin** [comment]
Twitter changed their layout a bit, more significantly on the mobile version than the desktop version.

This should be fixed in v2.15.1 of the extension / v58 of the user script:

https://github.com/insin/tweak-new-twitter/releases/tag/v2.15.1

**Comment by 96312** [comment]
@insin The addon Version 2.15.0 on the firefox store has not been updated. Please push an update soon. Thanks for the bug fix and the extension in general! 👍

**Comment by insin** [comment]
I pushed it 4 days ago, AMO haven't approved the new version. It usually only takes a few minutes.

![firefox_rh5lcUBaR1](https://user-images.githubusercontent.com/226692/184602396-6045b1d6-2239-4f7c-9685-c0e6729af6e4.png)

**Comment by 96312** [comment]
That's a shame on their part. Either way, thanks for the update and follow up!
