### ISSUE TITLE
add 'add muted word' to more menu isn't working?

### ISSUE THREAD

**Issue by lazydaizy** [insin/tweak-new-twitter#134]
hi! this actually disappeared about a week ago that i first noticed, i just kept forgetting to see if i could report it anywhere. i really miss the add muted word shortcut, i hope this is just a bug. idk what info you actually need but my firefox is up to date; the extension is up to date; disabling all other extensions makes no difference; turning both tnt and the setting off and on again did nothing lol

**Comment by insin** [comment]
Looks like this was another victim of the recent Twitter update - I've figured out a fix for it, should be in the next version
