### ISSUE TITLE
Request: Disable "Received New Replies" in timeline checkbox

### ISSUE THREAD

**Issue by Ayal1** [insin/tweak-new-twitter#139]
![Twitter's "received new replies"](https://user-images.githubusercontent.com/11942617/194574391-ee33b192-50d9-42ef-9ab4-5ed5e70ee462.png)
It looks like this (at least in dark mode) and appears above the tweet author's name if anyone hasn't seen it.

Fairly simple, my twitter timeline keeps getting filled with "received new replies" usually from tweets from several days ago that I don't care about, usually ones that I haven't liked/retweeted/replied to from people that I follow but only occasionally interact with their tweets.

**Comment by insin** [comment]
This is in the algorithmic timeline, Tweak New Twitter should be keeping you on the chronological timeline, but there is an option to hide these if you have the algorithmic timeline visible for some reason

![Screen Shot 2023-02-02 at 3 55 51 am](https://user-images.githubusercontent.com/226692/216124177-a9e81aa5-874e-40a6-b5d6-dc9242aea1fa.png)
