### ISSUE TITLE
Related Tweets showing in individual tweet view

### ISSUE THREAD

**Issue by dtupper** [insin/tweak-new-twitter#140]
The unwanted "Related Tweets" section shows below tweets in the individual tweet view. 

Simple repro:
1. View an individual tweet
2. Look below responses for tweet

Expected: "Related Tweets" section is hidden

Actual: "Related Tweets" section is showing

**Comment by insin** [comment]
Has this gone back to being an A/B tested feature? I definitely used to have it, but I don't any more. I can only work on a fix for it when I'm seeing them.

**Comment by TheOpponent** [comment]
I'm starting to see extra tweets in single tweet pages, but without the "More Tweets" header, so they immediately follow replies and look like additional replies to the tweet now.

**Comment by SpeaktheSky** [comment]
Yeah this just started happening for me in the last 24-48 hours. Unchecking the "Hide More Tweets" option doesn't bring back the "More Tweets" header, either.
