### ISSUE TITLE
Add "https://tweetdeck.twitter.com/*" to Site access rules

### ISSUE THREAD

**Issue by jordanrvillarreal** [insin/tweak-new-twitter#144]
With TweetDeck being decommissioned by Twitter as a stand alone application, it gives an opportunity for the browser based TweetDeck to be improved upon with this extension.  Many options may not be applicable however ones like hiding the message drawer would be invaluable.  

Thank you

**Comment by insin** [comment]
Better Tweetdeck should have you covered:

https://better.tw/

**Comment by ShinyHunterRob** [comment]
I came here to look for this exact thing, but for one specific feature to be added.
Tweetdeck (the new one, RIP BTD) doesn't show the difference between legacy verified users and Blue subs. Is that something you can implement?
