### ISSUE TITLE
Feature: Remembering scroll position when switching Home and Retweets.

### ISSUE THREAD

**Issue by younyokel** [insin/tweak-new-twitter#147]
The option to separate retweets from home posts is enabled. On the Home tab, scroll down a bit and go to Retweets tab, then go back to the Home tab. The page refreshes, causing the scroll bar to go up and making it harder to track your previous page position.

My solution is to make the page not refresh on single click on the "Retweets" button from the Home tab, and the "Home" button from the Retweets tab. Refresh only when pressing "Home" button on Home tab, and "Retweets" button on Retweets tab.

**Comment by insin** [comment]
This is an artifact of the very unsmart way the Retweets tab is implemented - when you're viewing Latest Tweets, Tweak New Twitter is just hiding all retweets, and Twitter's infinite scrolling implementation keeps loadings more tweets to fill the window. When you click on the Retweets tab, Tweak New Twitter just switches to hiding everything but retweets. When you switch back and forward, whatever Twitter is doing to track your position in the timeline seems to get confused and brings you back to the top.

Your solution sounds like the right thing to do, but to make it work we'd have to figure out how Twitter keeps track of and restores your position in the timeline when you navigate back to it and trigger that functionality when switching between Latest Tweets and Retweets.

I know that built-in functionality already works with the way the Retweets tab is implemented, as I set it up to take you back to the Retweets tab if you navigate away to another page and then come back to the main timeline without clicking "Home", and Twitter still successfully restores your position in the Retweets timeline even though it doesn't really exist:

![firefox_Xx4Ll1FkAE](https://user-images.githubusercontent.com/226692/201515279-3984a757-ef63-4dbc-bd5b-d241b449c2fe.gif)

**Comment by insin** [comment]
I don't think this is doable as Folllwing and Retweets are the same timeline, but with different things hidden. This means Twitter's implementation for restoring scroll position is only going to be good for whatever the last one you looked at is
