### ISSUE TITLE
differentiate official vs paid blue check

### ISSUE THREAD

**Issue by yoshimo** [insin/tweak-new-twitter#151]
https://github.com/wseagar/eight-dollars is a nice idea to make this easier to tell apart

https://github.com/wseagar/eight-dollars/raw/main/assets/example.png

i think you should something similar

**Comment by insin** [comment]
This will be in the next release:

![firefox_70wpXipvpM](https://user-images.githubusercontent.com/226692/201265207-9990092b-346b-4c9b-8c04-8d1ec461a482.gif)

![chrome_0WoOemlkNv](https://user-images.githubusercontent.com/226692/201265226-0d07ef47-a53f-48a5-a25f-d0fae2fea5e1.png)

![firefox_ycMNSalxlm](https://user-images.githubusercontent.com/226692/201265231-c2c6721c-e43b-45b5-940c-a34264885a6d.png)

**Comment by insin** [comment]
Initial support released in v2.16.0
