### ISSUE TITLE
add 'hide replies mentioning blocked user'

### ISSUE THREAD

**Issue by leonoctem** [insin/tweak-new-twitter#153]
i know there's the 'Hide tweets quoting accounts you've blocked or muted' option which i have enabled, but I still see tweets in reply to someone who has me blocked and who i block in return. it's driving me nuts only seeing half a conversation. I dont want to see any of the conversation if possible!

**Comment by insin** [comment]
Is this in the timeline or in tweet threads elsewhere?

If you could provide a screenshot of what it looks like (and redact names/messages if you don't want to share those) I could have a look at this, as I don't think I've ever been in a conversation with someone I've mutually blocked on here.

**Comment by leonoctem** [comment]
it's on my timeline, but it's not a conversation i'm involved/mentioned in. it's people i follow who are replying to or mentioning the mutual blocked account and i can see the people i follows replies.

example of mutual block being mentioned on my timeline
![image](https://user-images.githubusercontent.com/73490659/201638155-a51b48bc-d330-4827-ba73-d87f1c801150.png)

I can't scroll back further than 5 hours on my timeline at the moment for some reason, so I haven't been able to get an example of my timeline showing replied to the mutually blocked account.

**Comment by insin** [comment]
Tweak New Twitter doesn't know anything about your block list and can only work with whatever tweets Twitter loads into the timeline, if they're showing you this in the open there's not much I can do about it.
