### ISSUE TITLE
Filtering out quote tweets only works if they aren't retweets.

### ISSUE THREAD

**Issue by tef** [insin/tweak-new-twitter#155]
If you set up the extension to filter out quote tweets from the main timeline, but not retweets, quote tweets still appear if they're retweeted by someone you follow.

I'm not sure if "quote tweets should be treated as quote tweets even if they're retweeted" is the right choice here, someone might want to filter out all retweets.

**Comment by insin** [comment]
Oof, yeah that's a miss, those should really be hidden if either filtering option is chosen but currently only the "is a retweet" part of them is considered.

![firefox_GoxnaJA3B2](https://user-images.githubusercontent.com/226692/202723056-08271b7e-950d-4e97-92d8-f2c637a9be3b.png)

**Comment by tef** [comment]
Thank you!
