### ISSUE TITLE
Request: block specific website 

### ISSUE THREAD

**Issue by 24bti192kHz** [insin/tweak-new-twitter#157]
In my timeline there are a lot of people that I follow and they keep promoting annoying  websites, but the website are specific so for example:
https://www.twitch.tv
https://www.youtube.com
https://curiouscat.live

so I just want a way to block sites so I don't see them in my timeline

**Comment by lazydaizy** [comment]
genuine q: is this not already achievable with the regular muted words feature?

**Comment by 24bti192kHz** [comment]
muting https://www.twitch.tv/ would not mute 
https://www.twitch.tv/user1
https://www.twitch.tv/user2
https://www.twitch.tv/user3 etc 
so it's useless

**Comment by insin** [comment]
This would be better done as a separate extension for this specific feature, scanning the contents of all tweets would just make this one even slower.
