### ISSUE TITLE
Extension removing quote tweet preview when my setting is on "do nothing" 

### ISSUE THREAD

**Issue by Zachruff** [insin/tweak-new-twitter#161]
![image](https://user-images.githubusercontent.com/70397032/204444374-54dd5c38-92cf-4f1e-a3f6-262e4cadca02.png)
![image](https://user-images.githubusercontent.com/70397032/204444445-48c6740d-2744-44f4-9ddd-b155dfccd104.png)
![image](https://user-images.githubusercontent.com/70397032/204444615-842221ff-e20c-4d72-b85b-b68be9b9e29f.png)

i get the second screenshot when i hae the extension with those settings, when it should look like the 3rd screenshot (extension disabled)

**Comment by insin** [comment]
The setting for this is under UI tweaks:

![image](https://user-images.githubusercontent.com/226692/204452422-bb423249-c170-4104-be64-d7f8ab7be13f.png)
