### ISSUE TITLE
Request:Need tweet source labels Features.

### ISSUE THREAD

**Issue by meetpateltech** [insin/tweak-new-twitter#164]
It's possible to bring back twitter for android/twitter for iPhone/twitter web app source labels on this extension via API?

**Comment by insin** [comment]
It doesn't look like this information is accessible in the UI now it's been removed, so I can't do this.

**Comment by Hans5958** [comment]
Userscripts such as https://greasyfork.org/en/scripts/462070-show-ctime-of-retweets can do this. Would implementing such feature in this extension out of reach?
