### ISSUE TITLE
Request: remove analytics button on own tweets 

### ISSUE THREAD

**Issue by ivalith** [insin/tweak-new-twitter#165]
Is there any way to revert the tweet layout to before the analytics button was added in and moved to the position the reply button is normally in?

New layout as of the last 48 hours:
![2022-12-22_03-50-02](https://user-images.githubusercontent.com/57418557/209095319-1d25e682-ab0b-4c60-8e20-9baefd4ac9e3.png)

Previous layout:
![2022-12-22_03-50-08](https://user-images.githubusercontent.com/57418557/209095326-8d30743b-f916-4606-9992-1b606124b802.png)

**Comment by insin** [comment]
Added in v2.20.0, no idea now long it'll take the extension stores to review and publish the new version over Christmas though.
