### ISSUE TITLE
Add option to remove "Views" counter from tweets

### ISSUE THREAD

**Issue by Jurtaa** [insin/tweak-new-twitter#168]
Recently, Twitter began rolling out a new "Views" counter which would basically appear alongside the regular likes and retweets counters. Obviously, this was met with backlash, some complaining it may cause demotivation in some. As such, it'd would be of great interest to allow people to hide this new counter when viewing tweets, when it does eventually roll out to desktop users.

**Comment by Jurtaa** [comment]
adding on to this, not only does it cause demotivation, it's just straight up clutter and makes the ui appear cramped. as seen [in this tweet](https://twitter.com/JeffPowerBaby/status/1606041473434132492).

**Comment by insin** [comment]
Added in v2.20.0, no idea now long it'll take the extension stores to review an publish it over Christmas though.
