### ISSUE TITLE
Doesn't work properly if twitter language is not english

### ISSUE THREAD

**Issue by Devocub** [insin/tweak-new-twitter#17]
bookmarks etc is not hided if twitter language is not english
https://twitter.com/settings/language

**Comment by schadEigentlich** [comment]
I can confirm this. Having Twitter set to Japanese made the add-on fail completely. Switching to English fixed it, but it would be nice if worked with other languages.

**Comment by k4yt3x** [comment]
In addition to UI element errors, I also have the problem of the text box hiding completely if CJK characters are typed into the input box.

![image](https://user-images.githubusercontent.com/21986859/83553950-8bf42000-a4fb-11ea-824a-10ee3bcf29ac.png)

The plugin has been nice so far, but this bug is rendering it unusable.
Looking forward to a fix.

**Comment by revanmj** [comment]
Who to follow is also not hidden when language is not English

**Comment by insin** [comment]
- [ ] Look for stable replacements for selectors which use `aria-label` and `.textContent.includes(...)` - for some of them there really was nothing else to latch onto but those attributes, but some were just reaching for the quickest thing. These will probably need to be different for mobile and desktop versions too, e.g. 
- [ ] The current language is reflected in the `<html>`'s `lang` attribute, so for everything else we'll have to create locale lookups and should even be able to use `lang` to switch between them on the fly.

**Comment by insin** [comment]
While poking around trying to get Puppeteer to switch languages then go to different bits of the app to get translations, I noticed that when you change language and hit save, Twitter requests a module from `https://abs.twimg.com/responsive-web/client-web/i18n/${languageCode}.${hash}.js`

These are some of the codes  (from the English translation file) they're using bits we need inside those modules:

"d126cb7c",Latest Tweets"
"ha8209bb","Home"
"d497b854","Retweets"
"bd7c039f","Quote Tweets"

**Comment by insin** [comment]
I've got Tweak New Twitter working in Irish ☘️ , this is the list of language strings I've managed to reduce it down to so far locally, and hoping to be able to use something other than the presence of the hidden "Quote Tweet" label for quote tweet detection:

```javascript
const locales = {
  /*
  template: {
    // Needed to add a new menu item
    ADD_MUTED_WORD: 'd768049b',
    // Home timeline title - used to detect which timeline we're on, needed to change <title>
    HOME: 'ha8209bb',
    // Latest Tweets timeline title - used to detect which timeline we're on, needed to change <title>
    LATEST_TWEETS: 'd126cb7c',
    // Easy identifier for a visible quote tweet - potentially replaceable?
    QUOTE_TWEET: 'c9d7235d',
    // Separated tweets timeline title when config.quoteTweets = 'separate' on its own
    QUOTE_TWEETS: 'bd7c039f',
    // Separated tweets timeline title when config.retweets = 'separate' on its own
    RETWEETS: 'd497b854',      
  },
  */
  en: {
    ADD_MUTED_WORD: 'Add muted word',
    HOME: 'Home',
    LATEST_TWEETS: 'Latest Tweets',
    QUOTE_TWEET: "Quote Tweet",
    QUOTE_TWEETS: 'Quote Tweets',
    RETWEETS: 'Retweets',
  },
  ga: {
    ADD_MUTED_WORD: 'Cuir focal balbhaithe leis',
    HOME: 'Baile',
    LATEST_TWEETS: 'Tweetanna is déanaí',
    QUOTE_TWEET: 'Cuir Ráiteas Leis',
    QUOTE_TWEETS: 'Luaigh Tvuíteanna',
    RETWEETS: 'Atweetanna',
  },
  ja: {
    ADD_MUTED_WORD: 'ミュートするキーワードを追加',
    HOME: 'ホーム',
    LATEST_TWEETS: '最新ツイート',
    QUOTE_TWEET: '引用ツイート',
    QUOTE_TWEETS: '引用ツイート',
    RETWEETS: 'リツイート',
  },
}
```

I'm also using "Shared Tweets" as the name of the timeline when both Retweets and Quote Tweets are separated out into the fake timeline, I wonder if there's already something in Twitter's locale data I could use instead? 🤔

**Comment by insin** [comment]
Noice?

![R1Kp1jrBEC](https://user-images.githubusercontent.com/226692/126608827-a3c55306-fa64-4ee9-bec9-2b4fb4d35afe.gif)

Can anyone who knows Japanese tell me if Google Translate's suggestion of 共有ツイート works for "Shared Tweets"?

In fact, if you know any of the other languages Twitter supports, a translation for "Shared Tweets" would be most welcome 😸
