### ISSUE TITLE
[Feature Request] Add a Block Button

### ISSUE THREAD

**Issue by JayFlowGT** [insin/tweak-new-twitter#170]
A way to complement the "Fast blocking" option by giving the option of displaying a block button next to the comment, retweet and like icons as well as others recently added to Twitter.

The extension "Twitter One Click Block" did this fine, not having confirmation dialogue either, but has not been updated with the many redesigns that Twitter has undergone recently and is now entirely unusable. So extending the capability of the already present faster blocking would be greatly appreciated, as I found myself using this added feature quite a lot.

**Comment by insin** [comment]
Sorry, there are already enough features to maintain in this extension, so this would be better done as a separate extension.
