### ISSUE TITLE
FYI, tweet "Views" are no longer shown

### ISSUE THREAD

**Issue by LaraSQP** [insin/tweak-new-twitter#173]
First of all, thanks a million for developing this extension.

The tweet views (simple analytics shown left-most) below a tweet have suddenly disappeared.

Thanks again.

**Comment by TheOpponent** [comment]
The views counter appears to have been relocated next to the timestamp.
![0002188](https://user-images.githubusercontent.com/8432212/211996870-8bd18329-06ef-447f-b760-08d800f6ba23.png)

**Comment by LaraSQP** [comment]
Thanks.
