### ISSUE TITLE
Tabs are back

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#181]
No more sparkle menu to "unpin" tabs like last time

![image](https://user-images.githubusercontent.com/226692/211871170-f0d2d47d-4ee3-4a58-8a59-46dcbd590007.png)

**Comment by insin** [comment]
...and they're gone again (for now)

**Comment by pikesaury** [comment]
![スクリーンショット 2023-01-14 062837](https://user-images.githubusercontent.com/37852075/212422759-a7fd28a6-6fdb-4f7e-9f92-56c9785a6fae.png)
I got the same screen too.
Retweets are not separated.

**Comment by quizotix** [comment]
> ![スクリーンショット 2023-01-14 062837](https://user-images.githubusercontent.com/37852075/212422759-a7fd28a6-6fdb-4f7e-9f92-56c9785a6fae.png) I got the same screen too. Retweets are not separated.

Same problem. Was fine yesterday but now this new update has got rid of the retweets separated tab. Anyway to revert back?

**Comment by seirogan** [comment]
In addition to this, the "full width timeline content" feature no longer works.

**Comment by insin** [comment]
None of the timeline features will work properly until I get a new version out which handles the tabbed timeline.

The plan is to hide the "For you" tab, insert a new "Retweets" tab after "Following" and hide the now-useless "Home" header, which will make things look like they did before, but also support using the new pinned list tabs if you use them:

![image](https://user-images.githubusercontent.com/226692/212455195-741fd979-1941-4756-88ca-46706c6a609b.png)

![image](https://user-images.githubusercontent.com/226692/212456677-6a9f7287-3590-41f4-bc4b-3427cc6165bf.png)

(Just taking notes while I'm poking about). To hide the For you tab, we need to hide the link inside it with `display: none`, then set the tab itself to `flex: 0`. If you hide the entire tab itself, it causes the left scroll button to always appear when you hover over the tabs.

![image](https://user-images.githubusercontent.com/226692/212456733-1707683f-3ab4-49b9-baba-5d01359f57b4.png)

**Comment by insin** [comment]
Progressing well:

https://www.youtube.com/watch?v=5brWbv3-yhw

**Comment by pikesaury** [comment]
Thank you for the wonderful job you did.
Can't wait to use it!

**Comment by Techwolf** [comment]
Not working for me. I am missing the retweet tab and have what pikesauy and quizotix posted.
