### ISSUE TITLE
Update "Hide views" setting to apply to new view counter placement

### ISSUE THREAD

**Issue by Jurtaa** [insin/tweak-new-twitter#182]
![image](https://user-images.githubusercontent.com/29545237/211877701-8d7bd940-22dc-4725-a44e-a7e204f6dafd.png)
Twitter now displays the view counter alongside the date and time of the tweet being published instead of being next to the other counters. The "Hide views" setting should be updated to reflect this new change.

**Comment by insin** [comment]
Already done in c8bf64b5f8d049240b39d578f93fd654614578a4, just awaiting release
