### ISSUE TITLE
Filtering seems to be broken

### ISSUE THREAD

**Issue by ghost573** [insin/tweak-new-twitter#183]
Tweets, retweets, likes and the "who to follow" ads don't seem to be filtered properly and is all mixed together.

**Comment by pauldavisthefirst** [comment]
also seen here, firefox 108.0 on linux

**Comment by insin** [comment]
Lots of things will be broken until we add support for the new tabbed timeline

**Comment by ghost573** [comment]
Not a problem, guess this issue isn't needed since you already know about what's broken.
