### ISSUE TITLE
Algo removal no longer working

### ISSUE THREAD

**Issue by Drael64** [insin/tweak-new-twitter#185]
With the updates to twitter with 'for you' and 'following', the extension provides rather inconsistent results. Sometimes both are displayed, sometimes one, and it does stay bound to one.

**Comment by insin** [comment]
Is this still happening? Which version are you using, on which browser?

**Comment by Kazard** [comment]
I've newly downloaded this extension today, and this seems to still be an issue. I'm using a slightly out of date version of Chrome, and the latest version of the extension.

**Comment by zeronullempty** [comment]
Latest version of firefox, same issue. Extension doesn't work at all, despite working for a few minutes.

**Comment by insin** [comment]
Can anyone it's not working for provide some screenshots of what you're seeing and which settings you've changed (if any)?

You can also gain access to Debug mode by expanding the Experiments setting and clicking the last paragraph 5 times, like so:

![gpEV9tET6o](https://user-images.githubusercontent.com/226692/213616045-2e0c0ca9-5dda-4b76-ae29-db79a3531d99.gif)

If someone could do that and show me what gets logged in the F12 developer console that would be useful. e..g this is what it looks like for me when the home timeline algorithm removal is working:

![image](https://user-images.githubusercontent.com/226692/213616286-1cd95bbe-6185-4a04-86ce-28491213e55c.png)

**Comment by Kazard** [comment]
[twitter](https://i.gyazo.com/e62ab62242d4a9d815740dc1063bad8b.png)
  [settings](https://i.gyazo.com/8fb46e2b93b211c650af578bc3076278.png)
  [more](https://i.gyazo.com/bd1e801e37bd0aca9a639c9e6eb585ef.png)
  [more](https://i.gyazo.com/3c9a9d446694e7461778fc2088d9af23.png)
  
and console log
[twitter.com-1674191808172.log](https://github.com/insin/tweak-new-twitter/files/10463377/twitter.com-1674191808172.log)

**Comment by insin** [comment]
This line makes me think the main script is somehow being added to the page twice, trying to figure out and reproduce how that could happen:

> tweak-new-twitter.user.js:1 Uncaught SyntaxError: Identifier 'lang' has already been declared (at tweak-new-twitter.user.js:1:1)

**Comment by Kazard** [comment]
Various adblockers but only one specifically meant to interact with twitter: https://chrome.google.com/webstore/detail/twitter-large-thumbnails/lhmanalklfkgpfkinflfepcepbgkpmai

**Comment by zeronullempty** [comment]
I had to disable the Eight Dollars extension to get this one to work

https://github.com/wseagar/eight-dollars

**Comment by Kazard** [comment]
Crap, I had that and had forgotten about it. Removing it cleared up all of my issues too.

**Comment by insin** [comment]
You both get official Extension Detective 🕵️ badges

There is something I can do to mitigate this for people who have Eight Dollars or similar extensions installed now that I know what's happening.
