### ISSUE TITLE
Retweet Prompt Changed?

### ISSUE THREAD

**Issue by Kexus** [insin/tweak-new-twitter#187]
I can't find anything in the release notes about this so it may be twitter A/B testing, but recently (after 1/13 or 1/14), the behavior of the retweet button has changed. Instead of bringing up the "Retweet / Quote Tweet" prompt, it retweets by default. I have to click it again to get an "Undo Retweet" option and then a third time to quote tweet. 

Is this change caused by tweak new twitter? If so, how do I disable it?

**Comment by insin** [comment]
Disable the "Always use the Following (chronological) timeline" option until you have [v2.21.0](https://github.com/insin/tweak-new-twitter/releases/tag/v2.21.0) or later - it was released 2 days ago but the Firefox and Edge extension stores still haven't reviewed and enabled the new version.
