### ISSUE TITLE
[Feature Request] Change Share Button to Add to Bookmarks if Share is off and Bookmarks is on

### ISSUE THREAD

**Issue by thakyZ** [insin/tweak-new-twitter#188]
I noticed I couldn't add a tweet to my bookmarks even though the bookmarks side panel is enabled. Could you make a way to change the Share button to only have bookmark tweet or make it into an add to bookmarks button itself, if the share button feature is turned off and the bookmarks side panel is enabled? If you rather do it some other way, I won't mind, I just want to be able to add to bookmarks without the share button in some way.

**Comment by insin** [comment]
Sorry, due to the way Twitter is implemented it's difficult to replace built-in features like this and once done, requires a lot of maintenance to keep working, so I won't be adding it to this extension - could be an idea for a separate extension/user script though.
