### ISSUE TITLE
Add option to unhide number of replies

### ISSUE THREAD

**Issue by gensakudan** [insin/tweak-new-twitter#191]
I'm not sure if it's just me, but literally just now, Twitter for web browsers seems to have removed the reply counter for tweets (the little speech bubble icon with a number next to it). Not only does this now require one extra click from the user to comment on a tweet, it has also shifted all the other icons' positions.

Hopefully a setting can be added to bring this back to how it's supposed to be.

**Comment by insin** [comment]
Twitter moved the views counter, replies are where it used to be so they're getting hidden (#190)

This will be fixed in the next version
