### ISSUE TITLE
Unable to see reply count on tweet.

### ISSUE THREAD

**Issue by MrSkullium** [insin/tweak-new-twitter#194]
It seems like twitter has updated today and there's no option in the addon to hide or disable the reply count. 
Example shown in a random tweet.
![Screenshot (1547)](https://user-images.githubusercontent.com/66441517/213022287-ca90d2a9-9ff9-4afd-9fa6-e48fec3c31df.png)

**Comment by insin** [comment]
This was fixed in [v2.21.2](https://github.com/insin/tweak-new-twitter/releases/tag/v2.21.2), you should just need to update the extension.
