### ISSUE TITLE
Chrome: Opening a Twitter tab in background for 10 seconds causes script to fail

### ISSUE THREAD

**Issue by mcpower** [insin/tweak-new-twitter#198]
This issue occurs with both the Chrome extension (version 2.22.0) and the UserScript (version 88). Tested on a clean Chrome profile.

With Chrome 109, opening a Twitter page in the background, and waiting a few seconds before switching to the tab, causes Tweak New Twitter to not be injected. The culprit seems to be these lines:

https://github.com/insin/tweak-new-twitter/blob/62625cdfb562d3978847393637355288f7cd12c3/tweak-new-twitter.user.js#L3289-L3296

I suspect that Tweak New Twitter is being run, but the actual DOM isn't rendered until the user switches to the tab. Interestingly, Chrome renders the tab without a `<title>`, just the URL:

![image](https://user-images.githubusercontent.com/6015058/213863072-3a037517-9280-4b94-b2a2-90e68a06798b.png)

and it seems like hovering over the tab to activate Chrome's tab preview causes the DOM and `<title>` to be rendered.

**Comment by insin** [comment]
Would just removing the timeout altogether fix this?

If Twitter ever change their implementation so the one specific element you currently need to look at to determine whether it's in mobile or desktop mode is no longer there, 99.9% of users aren't going to notice the logged message anyway, so the result is still just "Tweak New Twitter broke".

**Comment by insin** [comment]
Looks like just removing the timeout will work - it seems to get the app wrapper immediately if you're not logged in and waits for `<title>` to appear (which is what drives all the functionality based on the current page), or if you're logged in, it waits for the app wrapper instead then gets the `<title>`.

**Comment by mcpower** [comment]
Yep, removing the timeout altogether would fix it too.

You bring up a good point re: "what if `#layers + div` doesn't work in the future". Removing the timeout would result in the rAF loop being run forever like a spinlock, and would presumably increase CPU and battery usage (although this may just be premature optimisation). Perhaps we could keep the timeout, and gracefully handle the null element case instead? Some ideas might be:

- A crude `window.alert()` telling users that something failed.
- Same as above, but as an unintrusive popup on the screen.
- Assume that most users are using Desktop, and hope for the best.

**Comment by insin** [comment]
Thanks for the bug report - the current plan for that is still "I see it when I check Twitter and fix it as quickly as possible" 😸 

Put this in as a quick fix but will swing back around to this after I'm finished getting the Safari versions ready.

**Comment by mcpower** [comment]
I have a fix at #199 which adds a rAF to the timeout, which also fixes this issue if you wanted to use a timeout in the future. Feel free to close that if it's not necessary.
