### ISSUE TITLE
Japanese Localization

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#201]
Since Tweak New Twitter seems to be popular in Japan at the moment, I've made the options page and extension name and description localizable, and created a translation file for Japanese in the following branch:

Branch: https://github.com/insin/tweak-new-twitter/tree/translation-ja

The tweep below kindly did their own translation in the form of an annotated image, but my ability to transcribe Japanese text from an image is exactly none 😿

https://twitter.com/mitragyna/status/1616348553944645632

If one of our Japanese users could update the `"message"` strings in the translation file below it would be most appreciated 🙏 

https://github.com/insin/tweak-new-twitter/blob/translation-ja/_locales/ja/messages.json

Edit: since I've already added some translations from Twitter's own locale data, the English file is here for comparison: https://github.com/insin/tweak-new-twitter/blob/master/_locales/en/messages.json

If your Operating System language is set to Japanese, I think testing it should be a case of running `npm install` to install web-ext then following these instructions to launch Tweak New Twitter in your browser of choice:

https://github.com/insin/tweak-new-twitter/blob/master/CONTRIBUTING.md#running-as-a-browser-extension

**Comment by MitoKurato** [comment]
Thanks for the great work!
Unfortunately, I don't understand programming at all, but I translated the file.
I would be honored if I could be of help.

https://www.dropbox.com/s/2i8p1vjowttrevc/tweak-new-twitter-Japanese%20Localization-by-MitoKurato.txt?dl=0

**Comment by insin** [comment]
These are amazing, thanks!

**Comment by MitoKurato** [comment]
I fixed the translation, so it would be helpful if you could download it by reloading the above URL.

**Comment by MitoKurato** [comment]
{
  "extensionName": {
    "message": "ツイツイなおしたったー",
    "description": "Must not exceed 45 characters"
  },
  "extensionDescription": {
    "message": "アルゴリズムコンテンツを取り除き、ニュースとトレンドを非表示にして、タイムライン上の共有ツイートを制御することで、UIを改善します",
    "description": "Must not exceed 132 characters"
  },
  "optionsPageTitle": {
    "message": "ツイツイなおしたったー　オプション機能"
  },
  "option-ignore": {
    "message": "そのまま",
    "description": "Option for not changing existing Twitter functionality - we don't use 'Ignore' for this in English as it could be mistaken to mean 'Hide'"
  },
  "option-hide": {
    "message": "非表示",
    "description": "Option for hiding things, e.g. algorithmic tweets, Twitter Blue checks"
  },
  "option-separate": {
    "message": "別タブで開く",
    "description": "Option for showing Retweets or Quote Tweets in a separate tab from the main timeline"
  },
  "unmuteButtonText": {
    "message": "ミュート解除",
    "description": "Button used in the options page to unmute a muted Quote Tweet"
  },
  "debugCountdownLabel": {
    "message": " (デバッグオプション: 有効にするには $DEBUG_COUNTDOWN$ を複数回クリック)",
    "description": "Displayed when the user clicks multiple times on the info text at the end of the Experiments section to enable debug mode",
    "placeholders": {
      "DEBUG_COUNTDOWN": {
        "content": "$1",
        "example": "3"
      }
    }
  },
  "reduceAlgorithmicContentOptionsLabel": {
    "message": "アルゴリズムコンテンツを取り除く"
  },
  "alwaysUseLatestTweetsLabel": {
    "message": "常にタイムラインを「フォロー中」（時系列順）にする"
  },
  "hideForYouTimelineLabel": {
    "message": "アルゴリズムによる「おすすめ」を非表示"
  },
  "hideSidebarContentLabel": {
    "message": "スライドバーの「今どうしてる？」「おすすめトレンド」等を非表示"
  },
  "showRelevantPeopleLabel": {
    "message": "ツイート閲覧時に「おすすめユーザー」を表示する"
  },
  "hideWhoToFollowEtcLabel": {
    "message": "タイムラインの「おすすめユーザー」「おすすめトピック」を非表示"
  },
  "hideExplorePageContentsLabel": {
    "message": "Exploreページの内容を非表示（検索のみに使用する）"
  },
  "hideMoreTweetsLabel": {
    "message": "ツイートの「もっと見る」を非表示"
  },
  "sharedTweetsOptionsLabel": {
    "message": "他のユーザーが共有したツイート"
  },
  "retweetsLabel": {
    "message": "リツイート"
  },
  "quoteTweetsLabel": {
    "message": "引用ツイート"
  },
  "hideUnavailableQuoteTweetsLabel": {
    "message": "ミュートやブロックしたアカウントが含まれる引用ツイートを非表示"
  },
  "mutableQuoteTweetsLabel": {
    "message": "ラベルのついたツイートをミュートする"
  },
  "mutableQuoteTweetsInfo": {
    "message": "「この会話をミュートする"」メニューを引用ツイートに追加",
    "description": "The translations for 'Mute this conversation' in tweak-new-twitter.user.js are from Twitter's own locale data"
  },
  "algorithmicTweetsOptionsLabel": {
    "message": "タイムライン上のアルゴリズムによる「おすすめ」を非表示"
  },
  "algorithmicTweetsWarning": {
    "message": "注意：大量のツイートを非表示にするとパフォーマンスが低下するおそれがあります"
  },
  "communityTweetsLabel": {
    "message": "あなたのコミュニティからのツイート"
  },
  "followeesFollowsLabel": {
    "message": "あなたがフォローしてる人のフォロワーからのツイート"
  },
  "likedTweetsLabel": {
    "message": "「いいね」されたツイート"
  },
  "repliedToTweetsLabel": {
    "message": "新しいリプライがありました"
  },
  "suggestedTopicTweetsLabel": {
    "message": "おすすめトピックのツイート"
  },
  "uiImprovementsOptionsLabel": {
    "message": "UIの改善"
  },
  "uninvertFollowButtonsLabel": {
    "message": "フォロー／フォロワーボタンの反転表示を解除"
  },
  "followButtonStyleLabel": {
    "message": "ボタンのスタイル"
  },
  "followButtonStyleOption-monochrome": {
    "message": "モノクロ"
  },
  "followButtonStyleOption-themed": {
    "message": "テーマ"
  },
  "navBaseFontSizeLabel": {
    "message": "ナビゲーションバーを通常のテキストフォント形式にする"
  },
  "dropdownMenuFontWeightLabel": {
    "message": "ドロップダウンメニューを通常のフォント太さにする"
  },
  "fastBlockLabel": {
    "message": "即ブロック（確認画面をスキップする）"
  },
  "addAddMutedWordMenuItemLabel-desktop": {
    "message": "もっと見るに「ミュートするキーワードを追加」を追加"
  },
  "addAddMutedWordMenuItemLabel-mobile": {
    "message": "スライドアウトメニューに「ミュートするキーワードを追加」を追加"
  },
  "hideVerifiedNotificationsTabLabel": {
    "message": "通知の「認証済み」タブを非表示"
  },
  "hideViewsLabel": {
    "message": "ツイート下部のアナリティクスのリンクを非表示"
  },
  "hideAppNagsLabel": {
    "message": "「アプリで開く」を非表示"
  },
  "uiTweaksOptionsLabel": {
    "message": "UIを微調整"
  },
  "dontUseChirpFontLabel": {
    "message": "Chirpフォントを使用しない"
  },
  "twitterBlueChecksLabel": {
    "message": "Twitter Blueの認証済みチェックマーク"
  },
  "twitterBlueChecksOption-replace": {
    "message": "Twitter Blueロゴに変更"
  },
  "tweakQuoteTweetsPageLabel": {
    "message": "引用ツイート閲覧時に引用元ツイートを非表示"
  },
  "hideMetricsLabel": {
    "message": "マトリクスを非表示"
  },
  "hideAllMetricsLabel": {
    "message": "すべて非表示"
  },
  "hideReplyMetricsLabel": {
    "message": "返信"
  },
  "hideRetweetMetricsLabel": {
    "message": "リツイート"
  },
  "hideLikeMetricsLabel": {
    "message": "いいね"
  },
  "hideQuoteTweetMetricsLabel": {
    "message": "引用ツイート"
  },
  "hideFollowingMetricsLabel": {
    "message": "フォロー／フォロワー"
  },
  "hideTotalTweetsMetricsLabel": {
    "message": "総ツイート数"
  },
  "hideUnusedUiItemsOptionsLabel": {
    "message": "使用しないUI項目を非表示"
  },
  "hideAccountSwitcherLabel": {
    "message": "アカウントの切り替え"
  },
  "hideMessagesDrawerLabel": {
    "message": "メッセージ入力"
  },
  "hideExploreNavLabel": {
    "message": "Explore（ナビゲーション項目）"
  },
  "hideCommunitiesNavLabel": {
    "message": "コミュニティ（ナビゲーション項目）"
  },
  "hideMessagesBottomNavItemLabel": {
    "message": "メッセージ（ナビゲーション項目）"
  },
  "hideBookmarksNavLabel-desktop": {
    "message": "ブックマーク（ナビゲーション項目）"
  },
  "hideTwitterBlueNavLabel-desktop": {
    "message": "Twitter Blue（ナビゲーション項目）"
  },
  "hideShareTweetButtonLabel": {
    "message": "ツイート下部のシェアボタン"
  },
  "hideTweetAnalyticsLinksLabel": {
    "message": "ツイート下部のアナリティクスリンク"
  },
  "hideMoreSlideOutMenuItemsOptionsLabel-desktop": {
    "message": "使用しない「もっと見る」メニューの項目を非表示"
  },
  "hideMoreSlideOutMenuItemsOptionsLabel-mobile": {
    "message": "使用しないスライドアウトメニューの項目を非表示"
  },
  "hideTwitterBlueNavLabel-mobile": {
    "message": "Twitter Blue"
  },
  "hideTopicsNavLabel": {
    "message": "トピックス"
  },
  "hideBookmarksNavLabel-mobile": {
    "message": "ブックマーク"
  },
  "hideListsNavLabel": {
    "message": "リスト"
  },
  "hideTwitterCircleNavLabel": {
    "message": "Twitterサークル"
  },
  "hideMomentsNavLabel": {
    "message": "モーメント"
  },
  "hideNewslettersNavLabel": {
    "message": "ニュースレター"
  },
  "hideAnalyticsNavLabel": {
    "message": "アナリティクス"
  },
  "hideTwitterForProfessionalsNavLabel": {
    "message": "Twitter  Pro"
  },
  "hideTwitterAdsNavLabel": {
    "message": "Twitter Ads"
  },
  "hideMonetizationNavLabel": {
    "message": "収益化"
  },
  "hideHelpCenterNavLabel": {
    "message": "ヘルプセンター"
  },
  "hideKeyboardShortcutsNavLabel": {
    "message": "キーボードショートカット"
  },
  "experimentsOptionsLabel": {
    "message": "実験的機能"
  },
  "reducedInteractionModeLabel": {
    "message": "インタラクションモードを減らす"
  },
  "reducedInteractionModeInfo": {
    "message": "ツイートの下にあるアクションバーを非表示（リプライのみで交流する）"
  },
  "fullWidthContentLabel": {
    "message": "タイムラインのコンテンツを全幅表示"
  },
  "fullWidthContentInfo": {
    "message": "サイドバーを非表示にして、タイムラインコンテンツを全幅表示にする"
  },
  "fullWidthMediaLabel": {
    "message": "メディア＆カードを全幅表示"
  },
  "verifiedAccountsLabel": {
    "message": "認証済みアカウント"
  },
  "verifiedAccountsOption-highlight": {
    "message": "ハイライト"
  },
  "verifiedAccountsInfo": {
    "message": "認証済みアカウントとのやり取りやツイートを強調、あるいは非表示にすることで2020年7月のTwitterハッキングの影響をシュミレートします"
  },
  "disableHomeTimelineLabel": {
    "message": "「ホーム」タイムラインを無効化"
  },
  "disableHomeTimelineInfo": {
    "message": "Twitterに時間を盗まれていませんか？「ホーム」タイムラインの利用を控えてみる"
  },
  "disabledHomeTimelineRedirectLabel": {
    "message": "「ホーム」タイムラインをリダイレクト"
  },
  "disabledHomeTimelineRedirectOption-notifications": {
    "message": "通知"
  },
  "disabledHomeTimelineRedirectOption-messages": {
    "message": "メッセージ"
  },
  "debugOptionsLabel": {
    "message": "デバッグオプション"
  },
  "debugLabel": {
    "message": "デバッグモード"
  },
  "debugInfo": {
    "message": "デバッグログを有効化し、ツイートデバッグ情報をタイムラインに表示"
  },
  "exportConfigLabel": {
    "message": "バグレポートの設定をエクスポート"
  }
}

**Comment by MitoKurato** [comment]
By the way, is it okay that I have made "Tweak New Twitter" into a Japanese title, "ツイツイなおしたったー(TwiTwiNaositatter)"?

If there is a problem, please change it back to "Tweak New Twitter".

The meaning of "ツイツイなおしたったー" is "I couldn't help but fix it."
(It's a joke based on "ツイ (twi)" and "ったー (tter)" .)

**Comment by insin** [comment]
Ah, thanks for letting me know - I'll revert it to Tweak New Twitter for now in the extension, but I might be able to use that elsewhere 😅

**Comment by insin** [comment]
Promotional tile for Japanese extension stores:

![chrome_small_promo_tile-ja](https://user-images.githubusercontent.com/226692/214120972-00d6a973-d344-4818-aede-41ef4ac81362.png)
