### ISSUE TITLE
[Userscript] Buffer extension hides Like button

### ISSUE THREAD

**Issue by MattDemers** [insin/tweak-new-twitter#209]
Not sure if this is something to bring up here, or with Buffer.

Having both the userscript and Buffer extension installed via Chrome means that the Buffer icon below tweets will hide the "Like" dialog.

Not sure if this is something that can be fixed.

![image](https://user-images.githubusercontent.com/7098804/214365522-ac71c9c2-cfa5-4344-a4f4-bb44b7d1f00c.png)
Above image is with both active.

![image](https://user-images.githubusercontent.com/7098804/214365637-454bb5e1-32ec-493c-8ef8-e5c0e009fb46.png)
Above image is without the Buffer Extension active.

**Comment by insin** [comment]
Thanks for letting me know - it looks like Buffer adds a new class name to the bar below tweets I should be able to use to avoid this when both are running at the same time

**Comment by MattDemers** [comment]
No worries! Sorry to add to your workload with an edge usecase.

**Comment by insin** [comment]
Not at all - I have a specific label for these bugs because it's not the first time there's been a conflict with other extensions.

**Comment by MattDemers** [comment]
No, the two to the far right are from another userscipt (Twitter Media Downloader) and tipping through Brave Browser (which I believe can be toggled). Both have never had any problems; I just noticed the Like button disappearing.
