### ISSUE TITLE
shouldHideTweet should check config.retweets first

### ISSUE THREAD

**Issue by roytam1** [insin/tweak-new-twitter#21]
if I set config.retweets = 'ignore', it still hides retweets.

**Comment by MeghunMak** [comment]
Looks like an issue with `config.hideWhoToFollowEtc` triggering RT hiding rather than the value of `config.retweets` 

With `config.hideWhoToFollowEtc` false then RTs appear again with `config.retweets` set to ignore

**Comment by seventy-two** [comment]
Looks like an issue with `config.hideWhoToFollowEtc` triggering RT hiding rather than the value of config.retweets

With `config.hideWhoToFollowEtc` false then RTs appear again with `config.retweets` set to ignore
