### ISSUE TITLE
Fix Twitter Blue checkmark replacement in Japanese (non-English?)

### ISSUE THREAD

**Issue by AliceMousie** [insin/tweak-new-twitter#223]
Twitter Blue checkmarks are not replaced on the user's page or in notifications timeline when Twitter language is set to Japanese.

**Comment by insin** [comment]
Thanks for the bug report.

- [ ] The Japanese version has さん at the end of `document.title`, which is breaking detection of Profile pages as it just ends with (@username) in English - we'll need to change how this is done

![firefox_WYCP9GpIXV](https://user-images.githubusercontent.com/226692/215298326-96cb9826-3eff-4de6-9d32-196efec4041c.png)

- [ ] It looks like the implementation of the verified check in "user liked your post" notifications has changed (again), as this is also broken the same way in English

![firefox_O8DRgXHxUR](https://user-images.githubusercontent.com/226692/215298329-3115289e-b81a-4678-b4e2-07d54a2caac3.png)

**Comment by insin** [comment]
Profile page detection was also completely broken for RTL languages, fixed for the next release

<details>
<summary>Japanese:</summary>
<img src="https://user-images.githubusercontent.com/226692/215304406-a774bf64-64f5-4f38-ab08-8212a0fc1f3a.png">
</details>

<details>
<summary>Arabic:</summary>
<img src="https://user-images.githubusercontent.com/226692/215304415-7413cf8c-8e6b-4dfa-86e5-1da44f960f9d.png">
</details>

**Comment by insin** [comment]
Fixed for now (again) - will be in the next release

![image](https://user-images.githubusercontent.com/226692/215305222-c421654f-fa8c-4697-9bc1-c42088e0c695.png)
