### ISSUE TITLE
Promoted Tweets being displayed in replies.

### ISSUE THREAD

**Issue by MrSkullium** [insin/tweak-new-twitter#224]
No matter who is tweeting it, how big or small, or if they're verified or not. I've been recently seeing ads/promoted tweets in the replies of tweets. I have ublock origin and there's no promoted tweets in the main timeline.
Example tweet
![Screenshot (1567)](https://user-images.githubusercontent.com/66441517/215596498-b5fa7154-6dd4-4a52-aec7-2c0b602f81cd.png)

**Comment by insin** [comment]
Which version are you using? Support for these media modal timelines was added a week ago in v2.24.0
