### ISSUE TITLE
[feature request] Add an option to hide "more tweets" when you open a tweet using a direct link from somewhere else

### ISSUE THREAD

**Issue by grishka** [insin/tweak-new-twitter#24]
There's this absolutely weird page with the tweet *you're interested in* collapsed at the top, then a block with a couple replies, and then "more tweets". Because engagement, apparently. Someone probably got a bonus or even a promotion for this. Anyway, the thread you're interested in is hidden behind an additional click. It shouldn't be. Would be nice to have an option to skip this superfluous page automatically.

**Comment by insin** [comment]
I have some WIP in a branch to automatically click the "View more replies" link to get rid of "More tweets", but it's a bit janky in use as "View more replies" takes part in windowed rendering, so if the tweet and the initial few replies are long enough you'll start scrolling then get a big visual jump when "View more replies" renders in and is automatically clicked.

https://github.com/insin/tweak-new-twitter/compare/fewer-tweets

Better than nothing though, so I'll play about with it a bit more then release it.

**Comment by grishka** [comment]
Actually, clicking the tweet at the top itself should also work, and it's always visible 🤔

**Comment by insin** [comment]
> Actually, clicking the tweet at the top itself should also work, and it's always visible 🤔

D'oh, of course! That works much better, we can start moving to the full thread view before the "More Tweets" view finishes rendering
