### ISSUE TITLE
Option to hide likes in feed

### ISSUE THREAD

**Issue by nhfo** [insin/tweak-new-twitter#28]
It would be very nice to be able to hide "likes" from feed. Likes are very annoying. I think people are lazy and like tweets to bookmark them. It is anyway not interesting to see what others liked.

**Comment by insin** [comment]
Hi, the extension should force Twitter to use the Latest Tweets timeline, which doesn't include likes.

If that ever changes, this is what we'll do: https://github.com/insin/tweak-new-twitter/issues/41#issuecomment-879629808
