### ISSUE TITLE
Hide tweets at will (suggestion)

### ISSUE THREAD

**Issue by ghost** [insin/tweak-new-twitter#31]
(didn't notice this was on git at first, i earlier left an identical post on the google chrome webstore lmao)

I don't know if this is viable, but I'd really like an option to hide tweets. As in, like, from a dropdown box, make it so I don't see a particular tweet ever again. Also, I want to do this to my own tweets without deleting them. I really hate how they go to the top of my latest tweets. If I'm in a particularly abusive argument, there's cases where my tweets is important to leave up, but seeing it can make me relive the argument in my head again and it's upsetting to me. So how about it, is that possible to implement potentially? Thanks.

**Comment by insin** [comment]
Yes, I think this should be possible :+1:
