### ISSUE TITLE
Customise which sidebar sections are hidden

### ISSUE THREAD

**Issue by AshFennix** [insin/tweak-new-twitter#40]
Would love to have just "Relevant people" show on the sidebar with the rest disabled as an option.

**Comment by insin** [comment]
I've had requests for other sections too, so let's make this one about customsing what you see on the sidebar 👍

**Comment by insin** [comment]
These are the 1-based positions the different sidebar element appear at in the sidebar on different pages:

```
Home:
Notifications:
Bookmarks:
Lists:
what's happening - 3
who to follow - 4
topics to follow - 5

Tweet:
relevant people - 3
what's happening - 4

Quote Tweets:
what's happening - 3
topics to follow - 4

Profile (with media):
You might like - 4
what's happening - 5
topics to follow - 6

Profile (of someone who's never tweeted any media):
You might like - 4
what's happening - 5
topics to follow - 6

Connect:
what's happening - 3
topics to follow - 4

Explore:
who to follow - 1
topics to follow - 2

Topics:
what's happening - 3
who to follow - 4

Search:
what's happening - 2
who to follow - 3
topics to follow - 4
```

We can use these to build CSS rules which only hide the configured parts on each page, then add classes to `<body>` to trigger them based on the current page.

We're already doing a simpler version of this to hide everything except useful parts (search input, search options etc.) in the sidebar.
