### ISSUE TITLE
Latest Tweets no longer works

### ISSUE THREAD

**Issue by dawnerd** [insin/tweak-new-twitter#42]
Twitter has disabled the option to use latest tweets outside of their mobile apps. Wonder if there's a way to bring it back.

This search works for the time being https://twitter.com/search?q=filter%3Afollows%20-filter%3Areplies&src=typed_query&f=live

**Comment by brechtcs** [comment]
Here is a userscript that still works (for now): https://github.com/furyutei/I_like_latest_tweets/blob/master/src/js/I_like_latest_tweets.user.js

**Comment by insin** [comment]
Twitter have been A/B testing removing the Latest Tweets timeline, refreshing the page usually brings it straight back
