### ISSUE TITLE
Suggestion: "Take Screenshot" and "Stamp This Tweet" Buttons

### ISSUE THREAD

**Issue by gesdemirei** [insin/tweak-new-twitter#53]
1- Sometimes I take screenshot tweets on Twitter. When I want to take screenshot, I zoom in page (like 150%), inspect profile picture and tweet's photo and update strings to original (sometimes it can be larger image) URL from default URL on in tweets and use screenshot tool on inspect to take screenshot.

For example [this tweet](https://twitter.com/inonuvakfi/status/1423176950739243008).
* Default Profil Picture's Photo: https://pbs.twimg.com/profile_images/1272811597531152384/ExrnCNWI_normal.jpg
* Original Profil Picture's Photo: https://pbs.twimg.com/profile_images/1272811597531152384/ExrnCNWI.jpg
* Default Tweet's Photo: https://pbs.twimg.com/media/E7upafuXoAo4cQF?format=jpg&name=small
* Original Tweet's Photo: https://pbs.twimg.com/media/E7upafuXoAo4cQF?format=jpg&name=orig

Normally this method is very time wasting and tough. But with you can take screenshot hd-quality with this method. Maybe you can make practice this.

2 - There is [an account](https://twitter.com/tweet_stamp) called tweetstamp.org that archiving and generating new URL for tweets on Twitter. Previously I could see tweetstamp link to use tweet ID [for example: https://twitter.com/Canan_Kaftanci/status/1423187867367526401 >> https://tweetstamp.org/1423187867367526401] using a browser extension called Swift Selection Search with a search URL [https://tweetstamp.org/{searchTerms}] But this site give errors with this method.

![Screen Shot 2021-08-05 at 12 17 59](https://user-images.githubusercontent.com/84249988/128348517-9b92400b-c3a5-4935-9a5a-068a7a2eb8b6.png)

If you don't want to see these errors, you need to write "@tweet_stamp stamp" on writing tweet bar. I don't like this writing things. Maybe you can make practice. Because this archiving and new link generating site is useful on Twitter. Your add-on is about Twitter.

**Comment by insin** [comment]
I don't want to add and maintain any more completely new functionality to Twitter in this extension which could be done as a separate extension
