### ISSUE TITLE
Suggestion: Allow disabling of certain metrics

### ISSUE THREAD

**Issue by truffl** [insin/tweak-new-twitter#54]
I currently use uBlock Origin to block Likes & Retweets as Tweak New Twitter only allows the disabling of all metrics.
Would be nice to have a tick-box of likes, retweets, replies, and followers/following all separate.

**Comment by insin** [comment]
Something like this?

![firefox_xQXFnTCBTe](https://user-images.githubusercontent.com/226692/128586882-2cf9faea-2806-46b8-a7cf-39f69da7eeed.png)

**Comment by truffl** [comment]
> Something like this?
> 
> ![firefox_KOftTUKZ5q](https://user-images.githubusercontent.com/226692/128587035-0040e891-ee18-4338-811e-07bf167435f7.png)

Yes this would be beautiful

Also bumping this suggestion below for consideration
https://github.com/insin/tweak-new-twitter/issues/25

**Comment by insin** [comment]
Released in v2.6

**Comment by truffl** [comment]
Sorry to revive this but just had an idea
Any way to add a check box that allows you to reveal disabled metrics by mousing over? Like moving mouse over the Like/Retweet button or Retweets/Likes hyperlink (on an open tweet) shows the number?
Also thanks for adding my suggestion
