### ISSUE TITLE
I Can't See Properly Tweets on Quote Tweets's Page 

### ISSUE THREAD

**Issue by gesdemirei** [insin/tweak-new-twitter#55]
When I want to see quote tweets, I see in these ways.

![Screen Shot 2021-08-09 at 23 19 12](https://user-images.githubusercontent.com/84249988/128769573-d06dafb4-db5e-472a-866b-0ea2257019fa.png)

![Screen Shot 2021-08-09 at 23 19 19](https://user-images.githubusercontent.com/84249988/128769659-90550948-2557-40fc-b4dc-6c4d7da078d8.png)

![Screen Shot 2021-08-09 at 23 19 25](https://user-images.githubusercontent.com/84249988/128769530-6c416484-6e2f-4322-a6e1-3eec502335be.png)

Is this problem's reason settings that I have selected or something?

![Screen Shot 2021-08-09 at 23 27 08](https://user-images.githubusercontent.com/84249988/128769896-7eabaff7-c485-40d2-8d58-aab2e7428a14.png)

**Comment by insin** [comment]
This is the "Pin the quote tweet when viewing Quote Tweets" setting, but we need to do something about media in quoted tweets, as it takes up too much room when it's pinned.

If we wrapped the media in a `<details>` it could look something like this instead:

Collapsed:

![firefox_iM7Qk0s8Kw](https://user-images.githubusercontent.com/226692/128832492-899042c9-72e0-4219-98ad-85fc728c2f7d.png)

Expanded:

![xFobGl3Nm7](https://user-images.githubusercontent.com/226692/128832546-d67595b5-5737-4c90-ae88-94671d01f0ac.png)

**Comment by gesdemirei** [comment]
I see. If we don't want to see scrolling problem on this page, we need to disable this setting. Maybe this setting would be useful on next releases. Thanks for your reply.

**Comment by gesdemirei** [comment]
Previously I could hide frames/buttons that I didn't wanted on Twitter using uBlock Origin. But when I see your extension, I deleted Twitter's string on uBlock Origin's my filters page.

I use those extensions now:
![Screen Shot 2021-08-10 at 23 06 13](https://user-images.githubusercontent.com/84249988/128928090-ef772e18-83ee-4a1f-a020-021cc538735c.png)
