### ISSUE TITLE
Fast blocking broken

### ISSUE THREAD

**Issue by truffl** [insin/tweak-new-twitter#57]
Block dialogue now shows up again as of recent
![2021-08-12 16_50_12 _ Twitter - Opera](https://user-images.githubusercontent.com/82072707/129274837-806fab5f-60e5-44a5-bba1-f68eb7cd0eeb.jpg)

**Comment by insin** [comment]
Looks like they've changed a couple of things which could be affecting this, which we also need to account for elsewhere. For one they're now setting an overflow style on `<html>`, which is causing the whole page to get reprocessed when popups appear, and we want to avoid that.

Perhaps it's time to bite the bullet and add "Block" to the list of translations we know about, so we can just use the button text.
