### ISSUE TITLE
Suggestion: Reveal hidden metrics on hover

### ISSUE THREAD

**Issue by truffl** [insin/tweak-new-twitter#58]
Possible to add a check box that allows you to reveal disabled metrics by mousing over? Like moving mouse over the Like/Retweet button or Retweets/Likes (on an open tweet) shows the number?

**Comment by insin** [comment]
I don't really want add more features to stuff in the Experiments section, and this one defeats the purpose of the experiment 🙂 Will potentially also make the options available as a popup button in the future which would make this easier to turn on and off at will
