### ISSUE TITLE
Suggestion: Hide more "More" menu items

### ISSUE THREAD

**Issue by truffl** [insin/tweak-new-twitter#59]
I only tend to use the "Settings and privacy" item (aside from Add muted word), so all of the others would be nice to hide (including Settings for those who don't use/want to see it).
Maybe even add function to remove the "More" button all together along with more hiding options

![image](https://user-images.githubusercontent.com/82072707/129411929-b8836b20-d8ec-4eff-a8b5-a7cc859884d5.png)

**Comment by insin** [comment]
I want to avoid being able to hide essential functionality you might only use once in a while, as people will forget it's Tweak New Twitter doing it and get confused.

This already happened with hiding the account switcher, as it used to hide the entire thing, which also removed the only way to log out of Twitter 😆

This is what it will get down to in the next version:

![firefox_JDtLK0oDYK](https://user-images.githubusercontent.com/226692/130001474-fff8c196-56c5-4204-83f7-b16d9ad8bb6e.png)

**Comment by insin** [comment]
Released in v2.10
