### ISSUE TITLE
Slow to load on Brave Desktop

### ISSUE THREAD

**Issue by Nosrick** [insin/tweak-new-twitter#61]
Not sure if this is a problem you'll look into, but I'm using this extension on Brave, and Twitter is loading _extremely_ slowly. About one tweet every ten seconds, and the page can become unresponsive. Turning off this extension solves the problem.

Unsure of what information to give you, so here's the usual system info:
Windows 10 Home 21H1
8Gb RAM
Brave 1.28.105

**Comment by Michael-Z-Freeman** [comment]
Also getting this on latest Microsoft Edge. Script is functional but tweets slow to load. Like and retweet functions very slow.
