### ISSUE TITLE
Selecting 'Hide "Who to follow", "Follow some Topics" etc. in the timeline' blocks certain desired content

### ISSUE THREAD

**Issue by deusexcalamus** [insin/tweak-new-twitter#63]
as above, with this option selected, at least one twitter user (https://twitter.com/axia_chan May have NSFW content) only shows the first couple tweets and nothing else in both the latest Chrome and Firefox versions of the extension. This screenshot is taken in Firefox (mostly because it's easier to screenshot there) but the issue is also present in Chrome.
Edit: It's not just that one twitter profile page, it seems to be on several others, including my own.
![image](https://user-images.githubusercontent.com/8674645/132748692-ae4a82a1-69cd-4b28-ba9b-57d046921e7e.png)

**Comment by ksbrar** [comment]
+1

**Comment by insin** [comment]
This should be fixed in v2.11.2
