### ISSUE TITLE
Can't see full profiles on Firefox

### ISSUE THREAD

**Issue by queerterpreter** [insin/tweak-new-twitter#65]
When I click a profile to see their tweets, I only see three or four—right until the "who to follow" section, which I see upon disabling—then empty space. If I disable the extension, even without reloading the page, the issue disappears. Is there an overlay somewhere that's interfering with seeing profiles?

**Comment by itsdoreiku** [comment]
I suggest disabling 'Hide "Who to follow", "Follow some Topics" etc. in the timeline' as per #63 for now and closing this issue

**Comment by insin** [comment]
This should be fixed in v2.11.2 - a Twitter markup change broke tweet detection, so Tweak New Twitter didn't know when to stop hiding things which appear after the "Who to follow" title in a profile's timeline
