### ISSUE TITLE
[Suggestion] Hide all but the first tweet of a thread.

### ISSUE THREAD

**Issue by clarence112** [insin/tweak-new-twitter#68]
I follow people who regularly make threads that are easily hundreds of tweets long, yet every tweet shows up individually on my timeline and their profile. (one example is `@Foone`)
It would be nice to have an option to have those threads be condensed down to just the first tweet (unless viewing the thread) to avoid clutter.

**Comment by insin** [comment]
This is too fiddly to do in this extension due to the way Twitter's timelines work
