### ISSUE TITLE
[Suggestion] Only show tweets with Video, Gifs or Images

### ISSUE THREAD

**Issue by TRR95** [insin/tweak-new-twitter#69]
I fallow a lot of artist and sometimes I wish I could only tweets with Video, Gifs or Images, hiding tweets that only have text. I hope you can turn this can be turned into a reality.

**Comment by Sakuukuli** [comment]
I agree, this is really the only feature I need from this extension. Maybe text tweets could be shown in a separate feed like retweets.

**Comment by insin** [comment]
This is a bit to specific of a feature for Tweak New Twitter, it would be better implemented in an extension related to media functionality in Twitter

**Comment by neuralnermal** [comment]
> This is a bit too specific of a feature for Tweak New Twitter, it would be better implemented in an extension related to media functionality in Twitter

Is there any chance that you might reconsider this functionality? I know this might be a niche thing, but I too use Twitter mainly as an art platform like OP.
