### ISSUE TITLE
Add options to put "Algorithmic tweets..." in a separate timeline

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [insin/tweak-new-twitter#70]
My suggestion is to create an alternative to "Hide" or "Do Nothing", that I think it's kinda "extreme".

![image](https://user-images.githubusercontent.com/3390598/134584064-38ac9f31-2832-434e-93ca-e007677fe9de.png)

**Comment by insin** [comment]
I had "Show in separate timeline" as an option when developing the "Algorithmic tweets in Home timeline" options, but it didn't work well.

The algorithmic content seems to come in waves, and when there isn't much or isn't currently any, when you try to view the separate timeline, Tweak New Twitter would just spin and spin, hiding hundreds of tweets trying to find algorithmic tweets to show.

**Comment by KlausEverWalkingDev** [comment]
I see... what if the extensions keeps a kind of "cache", maybe using the tweets that "hide" detects. And making a comparison to keep adding non-duplicate tweets to that cache and showing in a different tab. Maybe when it freezes (if that happens) it could show a message to stay a little in the main feed until it gathers more algorithmic tweets.

**Comment by insin** [comment]
I can't really add any functionality like this to Twitter because everything in a Tweet (even applying hover background colours) is done in React, as soon as you detach a tweet to try to do something new with it, it becomes functionally dead
