### ISSUE TITLE
Request: User profile pages: More image/video thumbnails than 6 on the right sidebar

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/tweak-new-twitter#77]
Request: User profile pages: More image/video thumbnails than 6 on the right sidebar
(all thumbs must be from twitter.com/username/media)

![image](https://user-images.githubusercontent.com/82726385/137918532-2e55700c-730d-4eaf-b9a5-f01c70d783d9.png)

Please add option to enable to 12 or 15 thumbs :)

**Comment by GreenDotBlue99** [comment]
Check out this extension for ideas:
https://chrome.google.com/webstore/detail/twemex-sidebar-for-twitte/amoldiondpmjdnllknhklocndiibkcoe

**Comment by insin** [comment]
Sorry, we can't really do that in this extension - due to the way Twitter works we'd have to effectively re-implement the entire feature
