### ISSUE TITLE
Hide "More Tweets" doesn't seem to be working

### ISSUE THREAD

**Issue by wave-dash** [insin/tweak-new-twitter#80]
If I click a link to a Tweet from outside of Twitter, I see the "More Tweets" thing under the replies. If I instead copy and paste the URL into my search bar, I don't get the "More Tweet" thing.

Neither case involves the "?s=20" affix in the URL, which I haven't seen in a long time.

**Comment by insin** [comment]
It looks like they've changed how this works, so we'll have to find a new way to work around it.

**Comment by TheOpponent** [comment]
I'm using Vivaldi and I don't believe the Hide "More Tweets" option has ever worked for me. The more tweets always appears even when clicking on a tweet link from TweetDeck.

**Comment by insin** [comment]
I can't even see this section when I'm logged in any more, no matter how I try to (clicking on Tweets from external sites, from Google search results, manually adding query parameters), only if I'm logged out.

Updating the implementation to at least work in that scenario.
