### ISSUE TITLE
First thing i see on twitter after installing the addon...

### ISSUE THREAD

**Issue by Luke-L** [insin/tweak-new-twitter#82]
![twitter sucks](https://user-images.githubusercontent.com/19858052/145735293-344b3c54-99b4-47de-aad8-eb9b0eab00e0.JPG)

any plans to remove this shit?

![image](https://user-images.githubusercontent.com/19858052/145735374-89f7e55e-06d3-43ee-ad10-877df1446fd5.png)

**Comment by truffl** [comment]
Would like to see this gone as well

**Comment by insin** [comment]
The problem with these is there's no way to force them to appear so I can test that code added to try to hide them does what it's supposed to.

I could try adding `data-testid="inlinePrompt"` to the selector that's used to identify timeline items containing headings like "Follow some Topics" etc., but I have no way to test that it actually works when this appears.

**Comment by Luke-L** [comment]
Hey man dont worry about it. This appears rarely enough that the rest of
the addon still works  great 👍
