### ISSUE TITLE
Feature Request: Conversations can be intense

### ISSUE THREAD

**Issue by deusexcalamus** [insin/tweak-new-twitter#86]
Don't suppose you can remove/suppress the 'heads up, conversations like this can be intense' thing, can you?

**Comment by insin** [comment]
Is there a reliable way to trigger it? I've never seen it.

**Comment by deusexcalamus** [comment]
https://twitter.com/TwitterSupport/status/1445824131040120835 I've only ever seen it once, mostly because I just tend to retweet/fav, I don't actively tweet or anything anymore.
