### ISSUE TITLE
"What's happening" visible on Profile

### ISSUE THREAD

**Issue by ghost** [insin/tweak-new-twitter#87]
Hello everybody, i'm just trying the app for the first time, and I love it.
Mainly I'm using the Tweak New Twitter extension to hide the annoying "What's happening" tool, i don't want to see it at all at any moment.
I want to use this board to point what it seems to be a minor bug: often I can still see the "What's happening" sidebar on my "Profile" page (not in the main timeline), it appears and disappears randomly. Just that. I was wondering if it was a bug of some sort.
Very glad to contribute, keep up the good work!
Gustavo

**Comment by insin** [comment]
Could you provide a screenshot of what you see when this happens?

There's a bit of logic around what's hidden in the profile sidebar, as some people don't have any media tweets, so Tweak New Twitter tries to determine if there are any media tweet images in the sidebar. Something related to that could be going wrong.
