### ISSUE TITLE
Possible using this add-on could lead to your account being temporarily suspended/shadowbanned on Twitter?

### ISSUE THREAD

**Issue by 4chanx** [insin/tweak-new-twitter#88]
Sorry,  not very familiar with github, but I don't know where else to report this. I've been using Twitter for a long time, and I recently installed this add-on for Firefox about 2-3 months ago. Since then, I had the suspicion my replies weren't being seen by others, so I tested it using this site: https://hisubway.online/shadowban/

And I was indeed able to confirm my replies were being "deboosted". The timing lines up pretty well with when I started using this add-on, so I was wondering if there could possibly be a connection, and if anybody else has encountered something similar. Thank you for you rtime.

**Comment by insin** [comment]
AFAIK shadowbans are based on things you do you with your account, like who you follow, what you tweet and retweet, what your profile contains etc.

Tweak New Twitter doesn't affect any of that - most of what it does is using CSS and changing element styles to hide things, and the rest is using Twitter's own UI to do things like switch to the Latest timeline, none of which should even be detectable by Twitter.
