### ISSUE TITLE
it seems that many features stopped working 

### ISSUE THREAD

**Issue by cool80z** [insin/tweak-new-twitter#90]
Using the Firefox add on and things like topics you may like and advertisements are showing up. It worked flawlessly before.  Thank You for your dedicated work for this project.

**Comment by sethidden** [comment]
This is a bit vague so thought I'd provide an example:
![image](https://user-images.githubusercontent.com/5359825/152678347-eb44a930-0acf-44e3-b63c-733d3a8296bc.png)
![image](https://user-images.githubusercontent.com/5359825/152678332-f868790e-bf10-4b0d-b401-1cac363fdee5.png)

I though the algo content marked with a blue box in the first screenshot is handled by the "Hide who to follow [...] etc" option which is enabled in the screenshot above
