### ISSUE TITLE
Feature Request: Hide "[user] follows" algorithmic tweets

### ISSUE THREAD

**Issue by southrop** [insin/tweak-new-twitter#91]
Twitter has recently started aggressively pushing tweets from users that my mutuals follow but I don't follow, which lead me to looking for ways to remove it. I came across this extension as the most promising way to clean up my timeline, but it seems these tweets are not supported yet.

Sample tweet:
![image](https://user-images.githubusercontent.com/2568167/150953770-452f9b4a-827e-4021-afc2-d009dc2ae34f.png)

I don't know if this helps but I've also saved the HTML source of the tweet above in case it's some A/B test that's causing it to appear extra frequently for me.
[userfollowstweet.txt](https://github.com/insin/tweak-new-twitter/files/7932506/userfollowstweet.txt)

**Comment by insin** [comment]
Thanks,  I mustn't have seen this one before.

These are detected based on the SVG icon above the tweet, so just need to add that and an option to configure it.

**Comment by insin** [comment]
This is now available in v2.14.3
