### ISSUE TITLE
Variation on "replied" algorithmic tweet

### ISSUE THREAD

**Issue by southrop** [insin/tweak-new-twitter#92]
Hello again. Thanks for the rapid response on the followee' followers issue!

I found a variation on the "replied" algorithmic tweet that TNT doesn't filter properly, probably because it's a tree of replies.

Sample tweet:
No filter
![chrome_2022-01-26_10-36-52](https://user-images.githubusercontent.com/2568167/151090030-f5a03e54-25b4-4c61-be12-1ade1d240110.png)

Hidden
![image](https://user-images.githubusercontent.com/2568167/151090487-2aca478d-c0ca-4e71-8eff-724fa6dede07.png)

HTML Source (as txt)
[receivedrepliestweet.txt](https://github.com/insin/tweak-new-twitter/files/7938469/receivedrepliestweet.txt)

I'm still familiarizing myself with the codebase, but I believe it's because the isReplyToPreviousTweet function only checks the first child element of the reply line area element, and in the case of a tree, the line becomes the second child element (the first child element is the `└` part of the tree). Perhaps this might be resolved by adding a second check to see if `border-left-width` is 2px?

Here are screenshots of the respective elements highlighted in devtools so you can see the styles too.

![chrome_2022-01-26_11-02-48](https://user-images.githubusercontent.com/2568167/151091749-eb2a90b6-a3d9-4a4b-b28b-2b183d55413b.png)
![chrome_2022-01-26_11-03-15](https://user-images.githubusercontent.com/2568167/151091751-9a5334a1-28fa-4f90-b607-c494c6492c15.png)

**Comment by insin** [comment]
When I re-enabled the Home timeline to have a look, I even more variations on replies, which disappeared just after I took a screenshot of them, so I couldn't get a look at their markup.

All the replies here should say TWEET / REPLY once they're detected properly:

![firefox_t3fLZweqHp](https://user-images.githubusercontent.com/226692/151099193-c96c063b-8f67-4e5a-aeb9-5433f3065e21.png)

P.S. if you enable debug mode, Tweak New Twitter will show you what it's classified each timeline item as - open the options page, expand the Experiments section and click on the "Find yourself wasting time on Twitter?" paragraph 5 times.

![firefox_qRuhG23rMl](https://user-images.githubusercontent.com/226692/151099367-7c7df82c-d9bf-45f5-a980-274914894897.png)

**Comment by southrop** [comment]
Took me a while, but I finally got one like the one you screencapped, and saved the markup of the 4 relevant tweets. The reply thread (2nd and 3rd tweets) looks like a "regular reply thread" that's encapsulated in divs that form the the reply-tree markup.

![chrome_2022-01-27_11-04-37](https://user-images.githubusercontent.com/2568167/151279076-107ed6a5-c81d-4673-9b4b-bfa6de66ae0b.png)
[replythreadtree.txt](https://github.com/insin/tweak-new-twitter/files/7946962/replythreadtree.txt)

Unfortunately the twitter algorithm seems intent to never show the same thread tree twice so I've lost it for now...

**Comment by insin** [comment]
I haven't seen this variation appear since, closing for now. The current functionality for hiding stuff on the Home timeline is really just-in-case prep in case Twitter ever gets rid of Latest Tweets, but to be honest the Home timeline is unfixably bad in comparison
