### ISSUE TITLE
Bug: Add to list from a user's profile doesn't work

### ISSUE THREAD

**Issue by mtae** [insin/tweak-new-twitter#95]
When adding someone to a list from their profile, the UI element that pops up doesn't show your existing lists.

**Comment by insin** [comment]
Could this have been an API thing? Tweak New Twitter doesn't do anything to this list, and a test one I just created shows up.

![firefox_dCD7MTl4rY](https://user-images.githubusercontent.com/226692/154822104-5f7d8960-9791-4243-9186-65831d6e99d7.png)
