### ISSUE TITLE
High CPU usage and only a few tweets/retweets loaded on profile pages

### ISSUE THREAD

**Issue by globalistas** [insin/tweak-new-twitter#96]
I have TNT installed in my Vivaldi Browser using Tampermonkey and it basically craps out on profile pages. Only a few tweets/retweets of a profile are ever loaded and the CPU usage is quite high during this moment.

The issue with only just a few tweets/retweets loading also occasionally kicks in on the /home page (and one has to reload twitter to make it go away), but not enough to bother me.

Be glad to provide more details/debug info if needed.

**Comment by GreenDotBlue99** [comment]
How many extensions u have overall?
How many in Tampermonkey?
How many extensions/scripts for Twitter?

Add chrome://extensions to speed dial and turn off turn on Tampermonkey after changes. 

Also consider: New extensions engine is V3, it might be best to run TNT as separate extension as all V2 based extensions are SLOW and running V3 from V2 is more overhead.

U might also want to ditch Tampermonkey for Violentmonkey - it's super lightweight 🙂

**Comment by globalistas** [comment]
Thanks, I've since updated the script and it fixed the issue - turns out I was using a VERY old version. :)
