### ISSUE TITLE
Remove tracking parameters from tweet URLs copied to clipboard

### ISSUE THREAD

**Issue by fivefivefiver** [insin/tweak-new-twitter#99]
Recently, Twitter changed their "copy link to tweet" behaviour so that it adds tracking two parameters, `s` and `t` to the resulting URL.

Would it be possible to capture this behaviour and remove all URL parameters before the URL is sent to the clipboard?

**Comment by insin** [comment]
This would have to be done by waiting for the link to be written to the clipboard, reading it, then writing it back without the parameters.

I really don't want to add clipboard permissions to this extension for a minor feature, it looks dodgy even if done for legitimate reasons
